# Generated by Django 4.0.3 on 2022-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='projects_images'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='logo',
            field=models.ImageField(upload_to='technologies'),
        ),
    ]
