# Generated by Django 4.0.4 on 2022-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='back_end',
            field=models.ManyToManyField(blank=True, null=True, related_name='back', to='website.technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='front_end',
            field=models.ManyToManyField(blank=True, null=True, related_name='front', to='website.technology'),
        ),
    ]
